# Generated by Django 5.2.14 on 2026-08-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defUserModelprojapp', '0003_userdetails_state_userdetails_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('gst_no', models.CharField(max_length=15)),
                ('license_img', models.ImageField(blank=True, null=True, upload_to='license/')),
                ('restaurant_img', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
