# Generated by Django 5.2.14 on 2026-08-13 08:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defUserModelprojapp', '0005_vendordetials_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorDetials',
            new_name='VendorDetails',
        ),
    ]
