# Generated by Django 5.2.14 on 2026-08-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defUserModelprojapp', '0007_alter_vendordetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetails',
            name='password',
        ),
    ]
