# Generated by Django 6.0.4 on 2026-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
                ("year", models.PositiveIntegerField()),
                ("seater", models.PositiveBigIntegerField()),
                ("fuel_type", models.CharField(max_length=12)),
                ("milage", models.IntegerField()),
                ("cc", models.PositiveIntegerField()),
                ("country_origin", models.CharField(max_length=12)),
            ],
        ),
    ]
