# Generated by Django 5.2.14 on 2026-08-31 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=100)),
                ('est_year', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('engine_cc', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'petrol'), ('DIESEL', 'diesel'), ('EV', 'ev')], max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('seating', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='CBVapp.company')),
            ],
        ),
    ]
