# Generated by Django 5.2.14 on 2026-09-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBVapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='prodImg/'),
        ),
    ]
