# Generated by Django 5.2.14 on 2026-08-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='foodimg/')),
                ('category', models.CharField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('BEVERAGES', 'beverages'), ('DESSERTS', 'desserts')], max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
