# Generated by Django 5.2.14 on 2026-08-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defUserModelprojapp', '0008_remove_vendordetails_password'),
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendorDetailss', to='defUserModelprojapp.vendordetails'),
            preserve_default=False,
        ),
    ]
