# Generated by Django 5.2.14 on 2026-08-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_fooditems_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'breakfast'), ('STARTERS', 'starters'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('BEVERAGES', 'beverages'), ('DESSERTS', 'desserts')], max_length=50),
        ),
    ]
